### ISSUE TITLE
ReadMe empty

### ISSUE THREAD

**Issue by elisabaux** [purl-sanitizer/purl#2]
Hello, 
I am a student investigating the reproducibility of web privacy (compliance) measurements. And I have been trying to reproduce the results published in _"PURL: Safe and Effective Sanitization of Link Decoration"_ . 
I noticed the reference to a ReadMe file in another issue, but unfortunately, it is empty in the current repository. 
Could you provide insights into how the code was executed to obtain these results considering the missing ReadMe?  Any guidance on the code execution process for the data collection, configuration details and post-processing would be greatly appreciated.
Thank you for your help.

**Comment by iam-py-test** [comment]
FYI, the author gave a talk at the Ad Filtering Dev Summit which might answer some of your questions: https://yewtu.be/watch?v=-KkMWUaajhU&t=29282
Nevertheless I agree the README should contain information.
Thanks

**Comment by shaoormunir** [comment]
The pipeline is now cleaned up and the readme is also updated with instructions on how to run the pipeline end to end.
